server:
  port: 28761

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: register-eureka

  security:
    basic:
      enabled: true               # 开启基于HTTP basic的认证
    user:
      name: test                  # 配置登录的账号是user
      password: 123456

