server:
  port: 28762

spring:
  application:
    name: producer

  boot:
    admin:
      client:
        url: http://localhost:29091
        username: test
        password: 123456
  security:
    user:
      name: test
      password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://test:123456@localhost:28761/eureka/

  instance:
    preferIpAddress: true #以IP地址注册到服务中心，相互注册使用IP地址
    #ip-address: 192.168.1.1 #强制指定IP地址，默认会获取本机的IP地址
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"


